name: correction_CALLED
on:
  workflow_dispatch:
  issue_comment:
    types:
      - created

jobs:
  job_correction_CALLED:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == 'correction'
    runs-on: ubuntu-latest
    env:
      DIFF_CHECK: 0
    steps:
      - name: Github-Script
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
            
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-target-branch.outputs.result }}
      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: MIZOGUCHIKoki/ConfigFiles
          path: ConfigFiles
      - name: Copy files to current directory
        run: | 
          cp  ./ConfigFiles/tex_textlint/package.json ./
          cp  ./ConfigFiles/tex_textlint/.textlintrc.json ./
          cp  ./ConfigFiles/tex_textlint/package-lock.json ./
          cp  ./ConfigFiles/.gitconfig ./
            
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Fix typo
        run: |
          npx textlint --fix **/**.tex
      - name: Check changed files
        if: ${{ always() }}
        run: |
          rm -rf ConfigFiles node_modules package-lock.json package.json .textlintrc.json .gitconfig
          git add .
          git diff >> diff.txt
          cat diff.txt
          if [ -e diff.txt ];
          then
            $DIFF_CHECK=1
          fi
      - name: Push to " ${{ steps.set-target-branch.outputs.result }} Branch "
        if: ${{ env.DIFF_CHECK == 1 }}
        run: | 
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git push origin HEAD
