name: correction_CALLED
on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
      - edited

jobs:
  job_correction_CALLED:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == 'correction'
    runs-on: ubuntu-latest
    env:
      # if DIFF_CHECK=0 then **/**.tex files was not changed by textlint.
      DIFF_CHECK: 0      
    steps:
      - name: Github-Script
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
            
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-target-branch.outputs.result }}
        
      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: MIZOGUCHIKoki/ConfigFiles
          path: ConfigFiles
      - name: Copy files to current directory
        run: | 
          cp  ./ConfigFiles/tex_textlint/package.json ./
          cp  ./ConfigFiles/tex_textlint/.textlintrc.json ./
          cp  ./ConfigFiles/tex_textlint/package-lock.json ./
          cp  ./ConfigFiles/.gitconfig ./
            
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Correct
        run: |
          npx textlint --fix **/**.tex
      - name: Remove useless files
        if: ${{ always() }}
        run: |
          rm -rf ConfigFiles node_modules package-lock.json package.json .textlintrc.json .gitconfig
      - name: Check changed files
        run: |
          git diff >> diff.txt
          if [ -s diff.txt ];
          then
            echo "DIFF_CHECK=1" >> $GITHUB_ENV
          fi
          rm diff.txt
      - name: Commit to current branch
        if: ${{ env.DIFF_CHECK == 1 }}
        run: |
          git branch -a
          echo ${{ github.head_ref }}
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "Proofreading"
          git push origin HEAD
        env:
          GUTHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
