name: correction_CALLED
on:
#  workflow_dispatch:
  issue_comment:
    types:
      - created
      - edited

jobs:
  job_correction_CALLED:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == 'correction'
    uses: MIZOGUCHIKoki/COnfigFiles/.github/workflows/correction_main.yml@main
    secrets:
      gh_token: ${{ secrets.ACCESS_TOKEN }}
