name: fixtypo_CALLED
on:
  workflow_dispatch:
  issue_comment:
    types:
      - created

jobs:
  Job_fixtypo:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == 'fixed_typo'
    runs-on: ubuntu-latest
    steps:
      - name: Github-Script
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
            
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-target-branch.outputs.result }}
          
      - name: Deploy
        run: |
          tree
