name: run-textlint
on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: npm install
      - name: Run textlint
        run: npx textlint **/**.tex >> ./.textlint.log
      - name: Report if textlint finds problems
        if: ${{ failure() && github.ref != 'refs/heads/main'}}
        run: |
            # create body file
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            cat ./.textlint.log | sed "s/^/\` /" | sed "s/$/\`/" >> ./.textlint.log
            cat ./.textlint.log | sed "s/${pwd_esc}/### :policeman: ./g"  >> ./.body.txt
            cat .body.txt
            # pr comment
            gh pr comment --body-file ./.body.txt "${URL}"      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
