name: run-textlint
on: 
  push:
    branches:
      -main
  pull_request:
    paths:
      - '**/**.tex'
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Download Config files
        run: |
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/package-lock.json
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install packages via packages.json
        run: |
          rm -rf package.json .textlintrc.json
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/package.json
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/.textlintrc.json
          npm install
      - name: Run textlint
        run: |
            cat ./.textlintrc.json
            npx textlint -f checkstyle **/**.tex >> ./textlint.xml
            echo $?
      - name: Report if textlint finds problems
        if: ${{ failure() && github.ref != 'refs/heads/main'}}
        run: |
            cat ./textlint.xml
            wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/toHTML.xsl
            ls -a
            sudo apt-get install xsltproc libxml2-utils
            xmllint --format ./textlint.xml > ./ftextlint.xml
            sed 2i\<?xml-stylesheet\ type=text\/xsl\ href=./toHTML.xsl\ \?\> ./ftextlint.xml > ./ptextlint.xml
            sed -i 's/([^)]*)//g' ./ptextlint.xml
            sed -i 's/eslint.rules.//g' ./ptextlint.xml
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            xsltproc --output body.html ./toHTML.xsl ptextlint.xml
            cat body.html | sed "s/${pwd_esc}/:memo: ./g" >> ./.body.html
            gh pr comment --body-file ./.body.html "${URL}"      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
