name: run-textlint
on: 
  push:
    paths:
      - '**/**.tex'
  pull_request_target:
    paths:
      - '**/**.tex'
  
jobs:
  run-textlint_WF:
    uses: MIZOGUCHIKoki/ConfigFiles/.github/workflows/textlint_main.yml@main
    secrets:
      gh_token: ${{ secrets.ACCESS_TOKEN }}
