name: run-textlint-minimum
on: 
  push:
jobs:
  run-textlint-minimum:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npx textlint **/**.tex >> ./.textlint.log
      - if: ${{ failure() }}
        run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
      - name: Report if textlint finds problems
        run: |
          if [ -e ./.textlint.log ]; then
           # create body file
           pwd_esc=$(pwd | sed 's/\//\\\//g')
          cat ./.textlint.log | sed "s/${pwd_esc}/### :policeman: ./g" >> ./.body.txt
          # pr comment
          gh pr comment --body-file ./.body.txt "${URL}"
          fi        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
