name: reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog-check:
    name: reviewdog (check)
    runs-on: ubuntu-latest
    steps:
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Set up node
        uses: actions/setup-node@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: pat-s/always-upload-cache@v2.1.3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: install dependencies
        run: |
          npm install 
      - name: Execute textlint
        run: |
          sudo touch ./textlint.log
          sudo echo | npx textlint -f checkstyle **/**.tex >> ./textlint.log
          sudo echo textlint.log
