name: run-textlint
on: 
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/**.tex'
      - '**/**.yml'
jobs:
  run-textlint:
    permissions:
      pull-requests: write
    uses: MIZOGUCHIKoki/ConfigFiles/.github/workflows/textlint.yml@main
    with: 
      username: ${{ inputs.username }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
