name: run-textlint
on: 
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/**.tex'
      - '**/**.yml'
jobs:
  run-textlint:
    uses: MIZOGUCHIKoki/ConfigFiles/.github/workflows/textlint.yml@test-1
