name: run-textlint
on: 
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - typo_correction/**
      - test
jobs:
  run-textlint_WF:
    uses: MIZOGUCHIKoki/ConfigFiles/.github/workflows/textlint_main.yml@main
    secrets:
      gh_token: ${{ secrets.ACCESS_TOKEN }}
