name: run-textlint
on: 
  push:
    branches:
      -main
  pull_request:
    paths:
      - '**/**.tex'
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Download config files
        run: |
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/package-lock.json
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/package.json
      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Run textlint (avoiding error)
        run: |
            ls -a
            wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/.textlintrc.json
            ls -a
            cat ./.textlintrc.json
            npx textlint -f checkstyle **/**.tex >> ./textlint.xml
            echo $?
      - name: Report if textlint finds problems
        if: ${{ failure() && github.ref != 'refs/heads/main'}}
        run: |
            wget https://raw.githubusercontent.com/MIZOGUCHIKoki/ConfigFiles/main/tex_textlint/toHTML.xsl
            sudo apt-get install xsltproc libxml2-utils
            xmllint --format ./textlint.xml > ./ftextlint.xml
            sed 2i\<?xml-stylesheet\ type=text\/xsl\ href=./toHTML.xsl\ \?\> ./ftextlint.xml > ./ptextlint.xml
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            xsltproc --output body.html ./toHTML.xsl ptextlint.xml
            cat body.html | sed "s/${pwd_esc}/:memo: ./g" >> ./.body.html
            gh pr comment --body-file ./.body.html "${URL}"      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
