name: run-textlint
on: 
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/**.tex'
  workflow_dispatch:

jobs:
  run-textlint:
    uses: MIZOGUCHIKoki/ConfigFiles/.github/workflows/textlint.yml@main
    secrets:
#      gh_token: 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
